function tests = configurationTests()

tests = struct('functionHandle',[],'name',{},'expectedValue',{});

test = struct('functionHandle',@testCreateConfig001,...
              'name','Create basic configuration',...
              'expectedValue',true);
tests(end+1)=test;


test = struct('functionHandle',@testCreateConfig002,...
              'name','Create basic configuration with a modified parameter',...
              'expectedValue',true);
tests(end+1)=test;

test = struct('functionHandle',@testCreateConfig003,...
              'name','Create basic configuration with CV and SV to save',...
              'expectedValue',true);
tests(end+1)=test;


test = struct('functionHandle',@testCreateConfigSS001,...
              'name','Create Steady State configuration',...
              'expectedValue',true);
tests(end+1)=test;
